In [5]:
import pymysql
import csv

conn = pymysql.connect(host='localhost', user = 'scott', password = 'tiger', db = 'hydrogen', charset = 'utf8')
curs = conn.cursor()
sql = "insert into user (번호, 구축연도, 충전소명, 지역-대분류, 주소, 용도, 위도, 경도) values (%s, %s, %s, %s, %s, %s, %s, %s)"

f = open('한국가스안전공사_수소충전소 현황_20240927.csv','r', encoding = 'utf-8')

rd = csv.reader(f)

for line in rd:
    curs.execute(sql, (line[0], line[1], line[2], line[3], line[4], line[5], line[6], line[7]))
    #print(line)
conn.commit()
conn.close()
f.close()

ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-대분류, 주소, 용도, 위도, 경도) values ('번호', '구축연도', '�' at line 1")

In [8]:
import pymysql
import csv

# 데이터베이스 연결 설정
conn = pymysql.connect(host='localhost', user='scott', password='tiger', db='hydrogen_data', charset='utf8')
curs = conn.cursor()

# SQL 쿼리 정의 (컬럼 이름을 백틱으로 감싸기)
sql = "INSERT INTO user (`번호`, `구축연도`, `충전소명`, `지역_대분류`, `주소`, `용도`, `위도`, `경도`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"

# CSV 파일 읽기
f = open('한국가스안전공사_수소충전소 현황_20240927.csv', 'r', encoding='utf-8')
rd = csv.reader(f)

# 첫 번째 행 건너뛰기 (헤더 제거)
next(rd)

# 데이터 삽입
for line in rd:
    # 각 행의 모든 열을 삽입할 수 있도록 수정
    curs.execute(sql, (line[0], line[1], line[2], line[3], line[4], line[5], line[6], line[7]))

# 변경사항 커밋
conn.commit()

# 연결 종료
conn.close()
f.close()

ProgrammingError: (1146, "Table 'hydrogen_data.user' doesn't exist")

In [9]:
## csv 파일과 mysql 연결

import pymysql
import csv

# 데이터베이스 연결 설정
conn = pymysql.connect(host='localhost', user='scott', password='tiger', db='hydrogen_data', charset='utf8')
curs = conn.cursor()

# 테이블 생성 쿼리 추가
create_table_sql = """
CREATE TABLE IF NOT EXISTS user (
    번호 INT NOT NULL,
    구축연도 INT NOT NULL,
    충전소명 VARCHAR(255) NOT NULL,
    지역_대분류 VARCHAR(255) NOT NULL,
    주소 VARCHAR(255) NOT NULL,
    용도 VARCHAR(50) NOT NULL,
    위도 DOUBLE NOT NULL,
    경도 DOUBLE NOT NULL,
    PRIMARY KEY (번호)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
"""

# 테이블 생성
curs.execute(create_table_sql)

# SQL 쿼리 정의 (컬럼 이름을 백틱으로 감싸기)
sql = "INSERT INTO user (`번호`, `구축연도`, `충전소명`, `지역_대분류`, `주소`, `용도`, `위도`, `경도`) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"

# CSV 파일 읽기
f = open('한국가스안전공사_수소충전소 현황_20240927.csv', 'r', encoding='utf-8')
rd = csv.reader(f)

# 첫 번째 행 건너뛰기 (헤더 제거)
next(rd)

# 데이터 삽입
for line in rd:
    # 각 행의 모든 열을 삽입할 수 있도록 수정
    curs.execute(sql, (line[0], line[1], line[2], line[3], line[4], line[5], line[6], line[7]))

# 변경사항 커밋
conn.commit()

# 연결 종료
conn.close()
f.close()

In [10]:
## sql에서 테이블 생성하여 저장!

import pymysql

# 데이터베이스 연결 설정
conn = pymysql.connect(
    host='localhost',
    user='scott',
    password='tiger',
    db='hydrogen_data',
    charset='utf8'
)

try:
    # 커서 객체 생성
    curs = conn.cursor()

    # SQL 쿼리 실행하여 데이터 읽기
    select_query = "SELECT * FROM user"
    curs.execute(select_query)

    # 조회된 데이터 가져오기
    rows = curs.fetchall()

    # SQL 파일 생성 및 데이터 삽입 쿼리 작성
    with open('user_data_backup.sql', 'w', encoding='utf-8') as f:
        # 테이블 구조 작성 (필요시 추가)
        f.write("USE hydrogen_data;\n")
        f.write("CREATE TABLE IF NOT EXISTS user (\n")
        f.write("    번호 INT NOT NULL,\n")
        f.write("    구축연도 INT NOT NULL,\n")
        f.write("    충전소명 VARCHAR(255) NOT NULL,\n")
        f.write("    지역_대분류 VARCHAR(255) NOT NULL,\n")
        f.write("    주소 VARCHAR(255) NOT NULL,\n")
        f.write("    용도 VARCHAR(50) NOT NULL,\n")
        f.write("    위도 DOUBLE NOT NULL,\n")
        f.write("    경도 DOUBLE NOT NULL,\n")
        f.write("    PRIMARY KEY (번호)\n")
        f.write(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n")

        # INSERT 구문 작성
        for row in rows:
            insert_query = f"INSERT INTO user (번호, 구축연도, 충전소명, 지역_대분류, 주소, 용도, 위도, 경도) VALUES ({row[0]}, {row[1]}, '{row[2]}', '{row[3]}', '{row[4]}', '{row[5]}', {row[6]}, {row[7]});\n"
            f.write(insert_query)

    print("Data successfully saved to 'user_data_backup.sql'.")

finally:
    # 연결 종료
    conn.close()

Data successfully saved to 'user_data_backup.sql'.